kind: namespace
apiVersion: v1
metadata:
  name: ${namespace}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-mavenapp-deployment
  namespace: ${namespace}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: java-mavenapp
  template:
    metadata:
      lables:
        app: java-mavenapp 
    spec:
      containers:
        - name: java-mavenapp 
          image: iad.ocir.io/idrbkizrtukj/java-maven-app-ssk:${BUILDRUN_HASH}
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: java-mavenapp-service
  namespace: ${namespace}
  annotations:
    service.beta.kubernetes.io/oci-load-balancer-shape: "10Mbps"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: java-mavenapp